version: '3.1'

services:
  mysql:
    image: mysql # Check for an ARM64-supported version
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=main
      - MYSQL_ROOT_USER=admin
      - MYSQL_PASSWORD=password
    networks:
      - database

  crudpy:
    container_name: crudpy
    build: ./python
    ports:
      - 8002:8000
    depends_on:
      - mysql
    networks:
      - database
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: crudpy

  crudgo:
    container_name: crudgo
    build: ./go
    ports:
      - 8001:8080
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: crudgo
    networks:
      - database

  phpmyadmin:
    image: arm64v8/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 300M
      VIRTUAL_HOST: host
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: host
      LETSENCRYPT_EMAIL: email
    networks:
      - database
    depends_on:
      - mysql

networks:
  database:
  grafana:
  k6:
