version: '3.1'

services:
  mysql:
    db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - database

  crudpy:
    container_name: crudpy
    build: ./python
    ports:
      - 8002:8000
    depends_on:
      - mysql
    networks:
      - database
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: crudpy

  crudgo:
    container_name: crudgo
    build: ./go
    ports:
      - 8001:8000
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: crudgo
    networks:
      - database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  database:
